apiVersion: apps/v1 #api版本
kind: Deployment #资源类型
metadata: #元信息
  labels: #标签
    app: nginx-deploy #自定义的kv
  name: nginx-deploy #资源名称
  namespace: default #所在的命名空间
spec:
  replicas: 1 #期望副本数
  revisionHistoryLimit: 10 #进行滚动更新后的，保留的历史版本数
  selector: #选择器
    matchLabels: #按照标签匹配
      app: nginx-deploy #匹配的标签
  strategy: #资源更新策略
    rollingUpdate: #更新配置
      maxSurge: 25%  #进行更新时，更新的个数最多可以超过期望个数的比例
      maxUnavailable: 25% #进行更新时，最大的不可用比例，表示在所有副本中，最多可以有多少不更新成功
    type: RollingUpdate #滚动更新
  template: #Pod模板
    metadata: #Pod元信息
      labels: #Pod标签
        app: nginx-deploy
    spec: #Pod期望信息
      containers:
      - image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        name: nginx #容器的名称
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
